/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.gabriel.genderecamento.menu;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import me.gabriel.genderecamento.api.Produto;
import me.gabriel.genderecamento.api.dao.ProdutoDAO;

/**
 *
 * @author gabri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        readJTable();
    }
    
    public void readJTable() {
        DefaultTableModel model = (DefaultTableModel) jTabela.getModel();
        model.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();
        
        for (Produto p: pdao.read()) {
            
            model.addRow(new Object[]{
                p.getCodigo(),
                p.getLocal(),
                p.getNome(),
                p.getQuantidade(),
                p.getLote()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCodigoTextArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jProdutoTextArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLoteTextArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jQuantidadeTextArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLocalTextArea = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Endereçamento de Produtos");
        setResizable(false);

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Int.", "Produto", "Lote", "Qtde.", "Local"
            }
        ));
        jTabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(0).setMinWidth(80);
            jTabela.getColumnModel().getColumn(0).setMaxWidth(80);
            jTabela.getColumnModel().getColumn(1).setMinWidth(300);
            jTabela.getColumnModel().getColumn(1).setMaxWidth(300);
            jTabela.getColumnModel().getColumn(2).setMinWidth(250);
            jTabela.getColumnModel().getColumn(2).setMaxWidth(250);
            jTabela.getColumnModel().getColumn(3).setMinWidth(80);
            jTabela.getColumnModel().getColumn(3).setMaxWidth(80);
            jTabela.getColumnModel().getColumn(4).setMinWidth(80);
            jTabela.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jLabel1.setText("Codigo:");

        jCodigoTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoTextAreaActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto:");

        jProdutoTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutoTextAreaActionPerformed(evt);
            }
        });

        jLabel3.setText("Lote:");

        jLoteTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoteTextAreaActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        jQuantidadeTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantidadeTextAreaActionPerformed(evt);
            }
        });

        jLabel5.setText("Local:");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrarMouseClicked(evt);
            }
        });
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLocalTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jProdutoTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jCodigoTextArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLoteTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jQuantidadeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(206, 206, 206))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCodigoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLoteTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProdutoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jQuantidadeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLocalTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCodigoTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCodigoTextAreaActionPerformed

    private void jProdutoTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutoTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProdutoTextAreaActionPerformed

    private void jLoteTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoteTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoteTextAreaActionPerformed

    private void jQuantidadeTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantidadeTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuantidadeTextAreaActionPerformed

    private void jButtonCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarMouseClicked

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed

        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        JTextField a = new JTextField();
        
        p.setCodigo(jCodigoTextArea.getText());
        p.setNome(jProdutoTextArea.getText());
        p.setLote(jLoteTextArea.getText());
        p.setQuantidade(jQuantidadeTextArea.getText());
        p.setLocal(jLocalTextArea.getText());
        dao.create(p);
        
        
        jCodigoTextArea.setText("");
        jProdutoTextArea.setText("");
        jLoteTextArea.setText("");
        jQuantidadeTextArea.setText("");
        jLocalTextArea.setText("");
        
        
        readJTable();
        
//        DefaultTableModel table = (DefaultTableModel) jTabela.getModel();
//        Object[] dados = {jCodigoTextArea.getText(), jProdutoTextArea.getText(), jLoteTextArea.getText(), jQuantidadeTextArea.getText(), jLocalTextArea.getText()};
//        table.addRow(dados);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonCadastrar;
    public static javax.swing.JTextField jCodigoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField jLocalTextArea;
    public static javax.swing.JTextField jLoteTextArea;
    public static javax.swing.JTextField jProdutoTextArea;
    public static javax.swing.JTextField jQuantidadeTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
